[package]
name = "multi-block-txns"
version = "0.1.0"
authors = ["arnav-deep <arnavd4@gmail.com>"]
edition = "2021"

[dependencies]
alloy = { version = "0.4.2", features = ["full"] }
anyhow = "1.0.89"
hex = "0.4.3"
reqwest = "0.12.8"
serde_json = "1.0.128"
tokio = { version = "^1.40.0", features = ["full"] }
