[package]
name = "oyster-serverless-executor"
version = "0.1.0"
edition = "2021"

[lib]
name = "serverless"
path = "src/lib.rs"

[[bin]]
name = "oyster-serverless-executor"
path = "src/main.rs"

[[bin]]
name = "cgroups-retriever"
path = "src/cgroups_retriever.rs"

[dependencies]
actix-web = "4"
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
ethers = "2.0.11"
hex = "0.4.3"
k256 = { version = "0.13.2", features = ["ecdsa", "ecdsa-core"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.16.1", features = ["full"] }

[profile.release]
strip = true
lto = true