[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-stream = "0.3"
anyhow = "1.0"
thiserror = "1.0"
chrono = "0.4"
clap = { version = "4.3.0", features = ["derive"] }

[[bin]]
edition = "2021"
name = "logger"
path = "src/main.rs"
