[package]
name = "kms-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["signer-local"] }
anyhow = "1.0.95"
axum = "0.8.1"
nucypher-core = "0.14.0"
rand = "0.8.5"
tokio = { version = "1.43.0", features = ["full"] }
