[package]
name = "http-on-vsock-server"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
clap = "4.4.7"
hyper = { version = "0.14.27", features = ["full"] }
tokio-vsock = "0.4.0"
